CREATE DATABASE IF NOT EXISTS books_db;
USE books_db;

CREATE TABLE Book (
	BookID INT AUTO_INCREMENT PRIMARY KEY,
    Author VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Publisher VARCHAR(255),
    BookYear INT
);

CREATE TABLE BookInLib (
	LibID INT AUTO_INCREMENT PRIMARY KEY,
    BookID INT,
    FOREIGN KEY (BookID) REFERENCES Book(BookID) ON DELETE CASCADE
);